apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mycluster-0
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.159
    path: "/var/nfs/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mycluster-1
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.159
    path: "/var/nfs/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mycluster-2
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.159
    path: "/var/nfs/pv2"
