apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 3
  router:
    instances: 1
  secretName: mypwds
  datadirVolumeClaimTemplate:
    storageClassName: slow
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 7Gi

