apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 3
  secretName: mypwds
  tlsUseSelfSigned: true
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    storageClassName: slow
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 7Gi


